name: Hoofzy_V2
version: 1.0.1+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_storage: ^2.0.3
  logger: ^1.1.0
  hexcolor: ^2.0.7
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  sizer: ^2.0.15  
  cached_network_image: ^3.2.2
  url_launcher: ^6.1.7
  store_redirect: ^2.0.1
  async_wallpaper: ^2.0.1
  package_info_plus: ^1.0.2
  device_info_plus: ^8.0.0
  google_mobile_ads: ^2.3.0
  in_app_review: ^2.0.6
  in_app_update: ^4.0.1
  wallpaper_manager_flutter: ^0.0.2
  flutter_cache_manager: ^3.1.2
  connectivity_plus: ^3.0.2
  firebase_messaging: ^14.1.4
  firebase_analytics: ^10.0.7
  flutter_local_notifications: ^12.0.4
  mailto: ^2.0.0-nullsafety.0
  lottie: ^2.1.0
  get_cli: ^0.2.30
  flutter_otp_text_field: ^1.1.0+2
  flutter_holo_date_picker: ^1.1.0

  firebase_auth: ^4.2.1
  google_sign_in: ^5.4.2

dev_dependencies: 
  flutter_lints: 2.0.1
  #flutter_launcher_icons_maker: "^0.10.1"
  flutter_launcher_name: "^0.0.1"

  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Hoofzy V2"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_logo.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/hoofzy/
    - assets/lottie/
    - assets/hoofzy/setting_up.png
    - assets/hoofzy/supper_sale.png
    - assets/hoofzy/furry_friend.png
    - assets/hoofzy/mesh_gradient.png
    - assets/hoofzy/train_pet.png
    - assets/hoofzy/training_service.png
    - assets/hoofzy/pet_training_service.png
    - assets/hoofzy/pet_service.png
    - assets/hoofzy/welcome_pet.png
    - assets/hoofzy/vetniray.png
    - assets/hoofzy/grooming.png
    - assets/hoofzy/legal_care.png
    - assets/hoofzy/travel.png
    - assets/hoofzy/winter_care.png
    - assets/hoofzy/nutrition.png
    - assets/hoofzy/artical_pet.png
    - assets/hoofzy/hot.png
    - assets/hoofzy/every_dawg.png
    - assets/hoofzy/i_am_pro.png
    - assets/hoofzy/nutram.png
    - assets/hoofzy/trending_community_image.png
    - assets/hoofzy/chat.png
    - assets/hoofzy/like.png
    - assets/hoofzy/home_icon.png
    - assets/hoofzy/training_icon.png
    - assets/hoofzy/community_icon.png
    - assets/hoofzy/shop_icon.png
    - assets/hoofzy/service_icon.png
    - assets/hoofzy/white_male.png
    - assets/hoofzy/white_female.png
    - assets/hoofzy/grey_male.png
    - assets/hoofzy/grey_female.png
    - assets/hoofzy/white_dog.png
    - assets/hoofzy/white_cat.png
    - assets/hoofzy/grey_dog.png
    - assets/hoofzy/grey_cat.png

    - assets/hoofzy/app_icon.png
    - assets/hoofzy/profile_placeholder.png
    - assets/hoofzy/query.png
    - assets/hoofzy/dog.png
    - assets/hoofzy/checked.png
    - assets/hoofzy/unchecked.png
    - assets/hoofzy/un_checked.png
    - assets/hoofzy/add.png
    - assets/hoofzy/minus.png
    - assets/hoofzy/question.png
    - assets/hoofzy/cat.png
    - assets/hoofzy/emoji.png
    - assets/hoofzy/setup_profile_img.png

    - assets/hoofzy/dog_avatar.png
    - assets/hoofzy/grey_bording.png
    - assets/hoofzy/grey_doggy.png
    - assets/hoofzy/grey_dogwalking.png
    - assets/hoofzy/grey_dropin.png
    - assets/hoofzy/grey_house_sitting.png
    - assets/hoofzy/them_bording.png

    - assets/hoofzy/background.png
    - assets/hoofzy/facebook.png
    - assets/hoofzy/google.png
    - assets/hoofzy/apple.png
    - assets/hoofzy/message.png
    - assets/hoofzy/login_image.png
    - assets/hoofzy/boarding_title.png
    - assets/hoofzy/boarding_1_image.png
    - assets/hoofzy/boarding_2_image.png
    - assets/hoofzy/boarding_3_image.png
    - assets/hoofzy/dog_quiz.png
    - assets/hoofzy/cat_quiz.png
    - assets/hoofzy/authro.png
    - assets/hoofzy/profile_review.png
    - assets/hoofzy/submit_pp.png
    - assets/hoofzy/home_back_title.png
    - assets/hoofzy/house_sitting.png
    - assets/hoofzy/drop_visit.png
    - assets/hoofzy/doggy_care.png
    - assets/hoofzy/dog_walking.png
    - assets/hoofzy/service_dog.png

    - assets/hoofzy/verified.png
    - assets/hoofzy/star.png
    - assets/hoofzy/repeat.png
    - assets/hoofzy/location_primary.png
    - assets/hoofzy/grp_chat.png
    - assets/hoofzy/chat_white.png

    - assets/hoofzy/small_dog.png
    - assets/hoofzy/medium_dog.png
    - assets/hoofzy/large_dog.png
    - assets/hoofzy/gaint_dog.png
    - assets/hoofzy/cancel.png
    - assets/hoofzy/report.png
    - assets/hoofzy/boarding_heart.png
    - assets/hoofzy/razor.png
    - assets/hoofzy/strip.png
    - assets/hoofzy/google_play.png
    - assets/hoofzy/pet_foot_placeholder.png

    - assets/lottie/cute_doggie.json
    - assets/lottie/super_sale_hang.json
    - assets/lottie/hang.json
    - assets/lottie/create_pet_profile.json
    - assets/lottie/congratulation_success_batch.json
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SfProBold.OTF
          weight: 700
        - asset: assets/fonts/SfProLight.OTF
          weight: 300
        - asset: assets/fonts/SfProMedium.OTF
          weight: 500
        - asset: assets/fonts/SfProRegular.OTF
          weight: 400
        - asset: assets/fonts/SfProSemibold.OTF
          weight: 600